version: '3.8'

services:
  web:
    build: .
    command: sh -c "python portfoliowebsite/manage.py runserver 0.0.0.0:1111 & streamlit run portfoliowebsite/StBionicHealth.py --server.port 2222 --server.headless true"
    volumes:
      - .:/code
      - /etc/letsencrypt/live:/etc/letsencrypt/live
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal
      - ./secrets:/code/secrets
    ports:
      - "1111:1111"
      - "2222:2222"
    depends_on:
      - db

